# Generated by Django 6.0.3 on 2026-03-23 18:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neologismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome do neologismo', max_length=50)),
                ('definicao', models.TextField(help_text='Descrição completa do significado')),
                ('contexto_uso', models.TextField(help_text='Frase de exemplo demonstrando o uso')),
                ('pronuncia', models.CharField(help_text='Formato fonético. Ex: /bis.coi.tar/', max_length=100)),
                ('classe_gramatical', models.CharField(help_text='Substantivo, Verbo, Adjetivo, etc.', max_length=50)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Lista de strings. Ex: ["Internetês", "Anglicismo"]')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10)),
                ('motivo_rejeicao', models.TextField(blank=True, help_text='Texto explicativo do admin ao rejeitar', null=True)),
                ('reativado_em', models.DateTimeField(blank=True, help_text='Data em que o admin reativou após rejeição', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
