# Generated by Django 6.0.1 on 2026-01-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neologismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(help_text='Nome do Neologismo', max_length=50)),
                ('significado', models.TextField(help_text='O que significa esse neologismo')),
                ('exemplo_de_uso', models.TextField(help_text='Exemplo de uso do neologismo no dia á dia')),
                ('aprovado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
