# Generated by Django 6.0.1 on 2026-01-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neologismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neologismo',
            name='autor',
            field=models.CharField(blank=True, default='Anônimo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neologismo',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='neologismo',
            name='termo',
            field=models.CharField(help_text='Nome do Neologismo', max_length=50, unique=True),
        ),
    ]
