# Generated by Django 6.0.3 on 2026-03-23 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neologismo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='neologismo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_neologismos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='neologismo',
            name='deslikes',
            field=models.ManyToManyField(blank=True, related_name='neologismos_rejeitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='neologismo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='neologismos_curtidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
