# Generated by Django 6.0.1 on 2026-03-12 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neologismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neologismo',
            name='deslikes',
            field=models.IntegerField(default=0, help_text='Número de deslikes do neologismo', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='neologismo',
            name='likes',
            field=models.IntegerField(default=0, help_text='Número de curtidas do neologismo', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
