# Generated by Django 6.0.3 on 2026-06-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neologismo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citacao', models.TextField(help_text='Frase/trecho onde o neologismo aparece')),
                ('fonte', models.CharField(blank=True, help_text='Quem disse ou onde foi publicado. Ex: "@usuario no X"', max_length=200)),
                ('link', models.URLField(blank=True, help_text='Link para a fonte original')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('neologismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextos', to='neologismo.neologismo')),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
    ]
