# Generated by Django 6.0.1 on 2026-03-18 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neologismo', '0002_neologismo_deslikes_neologismo_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neologismo',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='neologismo',
            name='likes',
        ),
        migrations.AddField(
            model_name='neologismo',
            name='deslikes',
            field=models.ManyToManyField(blank=True, related_name='neologismos_rejeitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='neologismo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='neologismos_curtidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
